# Imported Libraries

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import sklearn.metrics as metrics
import warnings
from tkinter import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import pickle
warnings.filterwarnings('ignore')

## Symptoms and Prognosis

In [13]:
trainDataset = pd.read_csv('training_data.csv')
testDataset = pd.read_csv('test_data.csv')

In [14]:
#list of all the symptoms
sympList = trainDataset.iloc[1,0:132]

#list of all the diagnosis
diagList = trainDataset.iloc[:,132]

In [15]:
sympx = trainDataset.iloc[:, 0:132].values
diagy = trainDataset.iloc[:, 132].values
sympx1 = testDataset.iloc[:, 0:132].values
diagy1 = testDataset.iloc[:, 132].values

# K-NEIGHBOURS ALGORITHMS

In [16]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(sympx)
x_test = sc_x.transform(sympx1)
clf1 = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p=2)
clf1.fit(x_train, diagy)
y_pred = clf1.predict(x_test)
print("----- Predicted Values -----")
print(y_pred)
print("\n\n----- Confusion Matrix -----")
print(confusion_matrix(y_pred,diagy1))
accuracy = accuracy_score(y_pred,diagy1)
print("\n\n----- Accuracy Score -----")
print(accuracy*100,"%")

----- Predicted Values -----
['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo' 'Impetigo']


----- Confusion Matrix -----
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


----- Accuracy Score -----
97.61904761904762 %


# NAIVE BAYES

In [17]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(sympx,np.ravel(diagy))

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
y_pred1 = gnb.predict(x_test)
print("----- Naive Bayes Algorithm -----")
print(y_pred1)
print("\n\n--- Confusion matrix ---")
conf_matrix=confusion_matrix(y_pred1,diagy1)
print(conf_matrix)
print("\n\n--- Accuracy ---")
print(accuracy_score(y_pred1, diagy1)*100,"%")

----- Naive Bayes Algorithm -----
['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo' 'Impetigo']


--- Confusion matrix ---
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


--- Accuracy ---
97.61904761904762 %


In [18]:
pickle.dump(clf1,open('model1.pkl','wb'))
pickle.dump(gnb,open('model2.pkl','wb'))